version: "3.3"

services:
  app:
    build:
      args:
        user: "${DOCKER_USER}"
        uid: "${DOCKER_UID}"
        ugroup: "${DOCKER_GROUP}"
        gid: "${DOCKER_GID}"
      context: ./
      dockerfile: Dockerfile
    image: digitalStore-website
    container_name: digitalStore-website
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - mysql
    volumes:
      - ./:/var/www
    networks:
      - digitalstoreepy.com
    environment:
      CONTAINER_ROLE: "${CONTAINER_ROLE}"
      APP_ENV: "${APP_ENV}"
      DOCKER_USER: "${DOCKER_USER}"
  nginx:
    image: nginx:alpine
    container_name: digitalstoreepy.com-nginx
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - digitalstoreepy.com
volumes:
  redis:
    driver: "local"

networks:
  digitalstoreepy.com:
    driver: bridge
